fastlane_version "1.109.0"

default_platform :ios

lane :beta do
  # build your iOS app
  gym(
    workspace: "../Alarm/Alarm.xcworkspace",
    scheme: "Alarm"
  )
end

# https://docs.fastlane.tools/actions/scan/
lane :test do
  scan(
    scheme: "Alarm"
  )
end
