name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
         path: Pods
         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
         restore-keys: |
          ${{ runner.os }}-pods-
      - name: Bundle install
        run: bundle install
      - name: Cocoapods
        run: bundle exec pod install
      - name: Build and Test
        run: bundle exec fastlane test
